// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'models/gym_record.dart';
import 'models/quran_record.dart';
import 'user_model.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
      id: const obx_int.IdUid(1, 2330274204898567250),
      name: 'User',
      lastPropertyId: const obx_int.IdUid(2, 2405913849048577657),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 8746995851234120891),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 2405913849048577657),
            name: 'password',
            type: 9,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(2, 2722864113348618513),
      name: 'QuranRecord',
      lastPropertyId: const obx_int.IdUid(3, 2529383389900348699),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 887501644122305752),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 5361648211564430169),
            name: 'date',
            type: 10,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 2529383389900348699),
            name: 'status',
            type: 9,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(3, 6914979119525690775),
      name: 'GymRecord',
      lastPropertyId: const obx_int.IdUid(4, 5314251093022566432),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 8908166188165153020),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 870929873526855590),
            name: 'date',
            type: 10,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 405182896040296833),
            name: 'status',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 5314251093022566432),
            name: 'reminderTime',
            type: 10,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[])
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore(
    {String? directory,
    int? maxDBSizeInKB,
    int? maxDataSizeInKB,
    int? fileMode,
    int? maxReaders,
    bool queriesCaseSensitiveDefault = true,
    String? macosApplicationGroup}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(getObjectBoxModel(),
      directory: directory ?? (await defaultStoreDirectory()).path,
      maxDBSizeInKB: maxDBSizeInKB,
      maxDataSizeInKB: maxDataSizeInKB,
      fileMode: fileMode,
      maxReaders: maxReaders,
      queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
      macosApplicationGroup: macosApplicationGroup);
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
      entities: _entities,
      lastEntityId: const obx_int.IdUid(3, 6914979119525690775),
      lastIndexId: const obx_int.IdUid(0, 0),
      lastRelationId: const obx_int.IdUid(0, 0),
      lastSequenceId: const obx_int.IdUid(0, 0),
      retiredEntityUids: const [],
      retiredIndexUids: const [],
      retiredPropertyUids: const [],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, obx_int.EntityDefinition>{
    User: obx_int.EntityDefinition<User>(
        model: _entities[0],
        toOneRelations: (User object) => [],
        toManyRelations: (User object) => {},
        getId: (User object) => object.id,
        setId: (User object, int id) {
          object.id = id;
        },
        objectToFB: (User object, fb.Builder fbb) {
          final passwordOffset = fbb.writeString(object.password);
          fbb.startTable(3);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, passwordOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final idParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          final passwordParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 6, '');
          final object = User(id: idParam, password: passwordParam);

          return object;
        }),
    QuranRecord: obx_int.EntityDefinition<QuranRecord>(
        model: _entities[1],
        toOneRelations: (QuranRecord object) => [],
        toManyRelations: (QuranRecord object) => {},
        getId: (QuranRecord object) => object.id,
        setId: (QuranRecord object, int id) {
          object.id = id;
        },
        objectToFB: (QuranRecord object, fb.Builder fbb) {
          final statusOffset = fbb.writeString(object.status);
          fbb.startTable(4);
          fbb.addInt64(0, object.id);
          fbb.addInt64(1, object.date.millisecondsSinceEpoch);
          fbb.addOffset(2, statusOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final idParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          final dateParam = DateTime.fromMillisecondsSinceEpoch(
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 6, 0));
          final statusParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 8, '');
          final object =
              QuranRecord(id: idParam, date: dateParam, status: statusParam);

          return object;
        }),
    GymRecord: obx_int.EntityDefinition<GymRecord>(
        model: _entities[2],
        toOneRelations: (GymRecord object) => [],
        toManyRelations: (GymRecord object) => {},
        getId: (GymRecord object) => object.id,
        setId: (GymRecord object, int id) {
          object.id = id;
        },
        objectToFB: (GymRecord object, fb.Builder fbb) {
          final statusOffset = fbb.writeString(object.status);
          fbb.startTable(5);
          fbb.addInt64(0, object.id);
          fbb.addInt64(1, object.date.millisecondsSinceEpoch);
          fbb.addOffset(2, statusOffset);
          fbb.addInt64(3, object.reminderTime?.millisecondsSinceEpoch);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final reminderTimeValue =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 10);
          final idParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          final dateParam = DateTime.fromMillisecondsSinceEpoch(
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 6, 0));
          final statusParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 8, '');
          final reminderTimeParam = reminderTimeValue == null
              ? null
              : DateTime.fromMillisecondsSinceEpoch(reminderTimeValue);
          final object = GymRecord(
              id: idParam,
              date: dateParam,
              status: statusParam,
              reminderTime: reminderTimeParam);

          return object;
        })
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [User] entity fields to define ObjectBox queries.
class User_ {
  /// See [User.id].
  static final id = obx.QueryIntegerProperty<User>(_entities[0].properties[0]);

  /// See [User.password].
  static final password =
      obx.QueryStringProperty<User>(_entities[0].properties[1]);
}

/// [QuranRecord] entity fields to define ObjectBox queries.
class QuranRecord_ {
  /// See [QuranRecord.id].
  static final id =
      obx.QueryIntegerProperty<QuranRecord>(_entities[1].properties[0]);

  /// See [QuranRecord.date].
  static final date =
      obx.QueryDateProperty<QuranRecord>(_entities[1].properties[1]);

  /// See [QuranRecord.status].
  static final status =
      obx.QueryStringProperty<QuranRecord>(_entities[1].properties[2]);
}

/// [GymRecord] entity fields to define ObjectBox queries.
class GymRecord_ {
  /// See [GymRecord.id].
  static final id =
      obx.QueryIntegerProperty<GymRecord>(_entities[2].properties[0]);

  /// See [GymRecord.date].
  static final date =
      obx.QueryDateProperty<GymRecord>(_entities[2].properties[1]);

  /// See [GymRecord.status].
  static final status =
      obx.QueryStringProperty<GymRecord>(_entities[2].properties[2]);

  /// See [GymRecord.reminderTime].
  static final reminderTime =
      obx.QueryDateProperty<GymRecord>(_entities[2].properties[3]);
}
